// Exercise data store — used before Exercise model is available
// Key: exercise ID, Value: exercise data map
// ignore_for_file: lines_longer_than_80_chars
const Map<String, Map<String, dynamic>> kExerciseData = {
  // ─── PUSH — Chest ───────────────────────────────────────────────────────────

  'barbell_bench_press': {
    'id': 'barbell_bench_press',
    'name': 'Barbell Bench Press',
    'muscle': 'Chest',
    'equipment': 'full_gym',
    'sets': 4,
    'reps': 8,
    'defaultKg': 60.0,
    'formCues': [
      'Pinch shoulder blades together and retract them before unracking',
      'Keep feet flat on the floor throughout the entire lift',
      'Lower the bar to mid-chest, not toward your neck or stomach',
      'Drive through your feet as you press to generate full-body tension',
      'Keep wrists stacked directly over elbows at the bottom position',
    ],
    'targetMuscles': [
      'Pectoralis major',
      'Anterior deltoids',
      'Triceps brachii'
    ],
    'swapAlternatives': ['dumbbell_bench_press', 'machine_chest_press'],
    'category': 'push',
  },

  'dumbbell_bench_press': {
    'id': 'dumbbell_bench_press',
    'name': 'Dumbbell Bench Press',
    'muscle': 'Chest',
    'equipment': 'home_dumbbells',
    'sets': 4,
    'reps': 8,
    'defaultKg': 20.0,
    'formCues': [
      'Sit on the bench edge, place dumbbells on thighs, kick them up as you lie back',
      'Keep a slight arch in your lower back with shoulder blades pinched together',
      'Lower dumbbells until elbows are just below bench level — feel the stretch',
      'Press the dumbbells in a slight arc toward each other at the top',
      'Control the descent for 2 seconds; avoid letting dumbbells flare wide',
    ],
    'targetMuscles': [
      'Pectoralis major',
      'Anterior deltoids',
      'Triceps brachii'
    ],
    'swapAlternatives': ['barbell_bench_press', 'machine_chest_press'],
    'category': 'push',
  },

  'machine_chest_press': {
    'id': 'machine_chest_press',
    'name': 'Machine Chest Press',
    'muscle': 'Chest',
    'equipment': 'full_gym',
    'sets': 3,
    'reps': 10,
    'defaultKg': 50.0,
    'formCues': [
      'Adjust seat so handles are at mid-chest height when seated',
      'Keep your back fully in contact with the pad at all times',
      'Push the handles straight out without locking out elbows fully',
      'Squeeze your chest at full extension before returning slowly',
      'Exhale on the press, inhale on the return — do not hold your breath',
    ],
    'targetMuscles': [
      'Pectoralis major',
      'Anterior deltoids',
      'Triceps brachii'
    ],
    'swapAlternatives': ['barbell_bench_press', 'dumbbell_bench_press'],
    'category': 'push',
  },

  'incline_dumbbell_press': {
    'id': 'incline_dumbbell_press',
    'name': 'Incline Dumbbell Press',
    'muscle': 'Upper Chest',
    'equipment': 'home_dumbbells',
    'sets': 3,
    'reps': 10,
    'defaultKg': 20.0,
    'formCues': [
      'Set bench to 30–45 degrees — steeper angles shift work to shoulders',
      'Keep your shoulder blades retracted and pinched throughout the set',
      'Lower the dumbbells to the upper chest, not to shoulder level',
      'Press in a slight arc, bringing the dumbbells toward each other at the top',
      'Avoid flaring your elbows too wide — keep them at 45–60 degrees from torso',
    ],
    'targetMuscles': [
      'Upper pectoralis major',
      'Clavicular head',
      'Anterior deltoids',
      'Triceps brachii'
    ],
    'swapAlternatives': ['incline_barbell_press', 'cable_flyes'],
    'category': 'push',
  },

  'incline_barbell_press': {
    'id': 'incline_barbell_press',
    'name': 'Incline Barbell Press',
    'muscle': 'Upper Chest',
    'equipment': 'full_gym',
    'sets': 3,
    'reps': 10,
    'defaultKg': 50.0,
    'formCues': [
      'Set bench at 30–45 degrees and position the bar in the rack accordingly',
      'Grip the bar slightly narrower than flat bench — shoulder-width or just outside',
      'Touch the bar to your upper chest on each rep for full range of motion',
      'Keep elbows tucked at about 45–60 degrees to protect the shoulder joint',
      'Unrack with straight arms; do not press out of the rack at an angle',
    ],
    'targetMuscles': [
      'Upper pectoralis major',
      'Clavicular head',
      'Anterior deltoids',
      'Triceps brachii'
    ],
    'swapAlternatives': ['incline_dumbbell_press', 'cable_flyes'],
    'category': 'push',
  },

  'cable_flyes': {
    'id': 'cable_flyes',
    'name': 'Cable Flyes',
    'muscle': 'Chest',
    'equipment': 'full_gym',
    'sets': 3,
    'reps': 12,
    'defaultKg': 15.0,
    'formCues': [
      'Set pulleys at shoulder height and stand in a split stance for stability',
      'Maintain a slight, fixed bend in your elbows throughout — do not pull with biceps',
      'Lead with your elbows and forearms as you bring handles together in front of you',
      'Squeeze your chest hard when handles meet; hold briefly before returning',
      'Return slowly under control — resist the weight on the way back for maximum stretch',
    ],
    'targetMuscles': ['Pectoralis major', 'Anterior deltoids'],
    'swapAlternatives': ['dumbbell_flyes', 'incline_dumbbell_press'],
    'category': 'push',
  },

  'dumbbell_flyes': {
    'id': 'dumbbell_flyes',
    'name': 'Dumbbell Flyes',
    'muscle': 'Chest',
    'equipment': 'home_dumbbells',
    'sets': 3,
    'reps': 12,
    'defaultKg': 10.0,
    'formCues': [
      'Lie flat on a bench holding dumbbells directly above your chest, palms facing each other',
      'Maintain a soft, fixed bend in the elbows — this is not a pressing movement',
      'Open your arms in a wide arc, lowering until you feel a deep chest stretch',
      'Bring the dumbbells back together by squeezing your chest, not swinging your arms',
      'Go lighter than you think — the stretch is the stimulus, not the weight',
    ],
    'targetMuscles': ['Pectoralis major', 'Anterior deltoids'],
    'swapAlternatives': ['cable_flyes', 'machine_chest_press'],
    'category': 'push',
  },

  'push_up': {
    'id': 'push_up',
    'name': 'Push-Up',
    'muscle': 'Chest',
    'equipment': 'home_bodyweight',
    'sets': 3,
    'reps': 15,
    'defaultKg': 0.0,
    'formCues': [
      'Place hands slightly wider than shoulder-width with fingers pointing forward',
      'Form a straight line from head to heels — brace your core and squeeze your glutes',
      'Lower your chest to within an inch of the floor, keeping elbows at 45 degrees',
      'Push the floor away explosively; do not let hips sag or pike up',
      'Breathe in on the way down, breathe out on the way up',
    ],
    'targetMuscles': [
      'Pectoralis major',
      'Anterior deltoids',
      'Triceps brachii',
      'Core'
    ],
    'swapAlternatives': ['dumbbell_bench_press', 'diamond_push_up'],
    'category': 'push',
  },

  // ─── PUSH — Shoulders ────────────────────────────────────────────────────────

  'overhead_press': {
    'id': 'overhead_press',
    'name': 'Barbell Overhead Press',
    'muscle': 'Shoulders',
    'equipment': 'full_gym',
    'sets': 3,
    'reps': 8,
    'defaultKg': 40.0,
    'formCues': [
      'Grip the bar just outside shoulder width with a full thumb-wrap grip',
      'Start with bar resting on the front of your shoulders, elbows slightly in front of bar',
      'Brace your abs, squeeze your glutes, and keep your ribcage down throughout',
      'Press the bar in a straight vertical line — move your head back slightly to clear it',
      'Lock out overhead with shrugged shoulders at the top — do not hyperextend your back',
    ],
    'targetMuscles': [
      'Anterior deltoids',
      'Lateral deltoids',
      'Triceps brachii',
      'Upper traps'
    ],
    'swapAlternatives': ['dumbbell_shoulder_press', 'lateral_raises'],
    'category': 'push',
  },

  'dumbbell_shoulder_press': {
    'id': 'dumbbell_shoulder_press',
    'name': 'Dumbbell Shoulder Press',
    'muscle': 'Shoulders',
    'equipment': 'home_dumbbells',
    'sets': 3,
    'reps': 10,
    'defaultKg': 15.0,
    'formCues': [
      'Sit on a bench with back support, or stand to engage more stabilizers',
      'Start with dumbbells at ear level, elbows at 90 degrees, palms facing forward',
      'Press straight up until arms are fully extended, dumbbells nearly touching at top',
      'Lower slowly and under full control — 2 seconds down for maximum tension',
      'Avoid arching your lower back; keep your core tight throughout the movement',
    ],
    'targetMuscles': [
      'Anterior deltoids',
      'Lateral deltoids',
      'Triceps brachii'
    ],
    'swapAlternatives': ['overhead_press', 'lateral_raises'],
    'category': 'push',
  },

  'lateral_raises': {
    'id': 'lateral_raises',
    'name': 'Lateral Raises',
    'muscle': 'Delts',
    'equipment': 'home_dumbbells',
    'sets': 3,
    'reps': 15,
    'defaultKg': 8.0,
    'formCues': [
      'Stand with dumbbells at your sides, a slight bend in the elbows',
      'Lead with your elbows, not your hands — imagine pouring water out of a jug',
      'Raise to shoulder height only — going higher loads the traps, not the delts',
      'Pause briefly at the top with a slight external rotation of the wrist',
      'Lower slowly over 3 seconds for maximum lateral delt time under tension',
    ],
    'targetMuscles': ['Lateral deltoids', 'Supraspinatus'],
    'swapAlternatives': ['cable_lateral_raises', 'dumbbell_shoulder_press'],
    'category': 'push',
  },

  'cable_lateral_raises': {
    'id': 'cable_lateral_raises',
    'name': 'Cable Lateral Raises',
    'muscle': 'Delts',
    'equipment': 'full_gym',
    'sets': 3,
    'reps': 15,
    'defaultKg': 10.0,
    'formCues': [
      'Set the cable pulley to the lowest position and hold the handle across your body',
      'Keep a slight bend in the working elbow throughout — this is not a straight-arm raise',
      'Raise the cable handle up and out to shoulder height in a smooth arc',
      'Cable provides constant tension at the bottom unlike dumbbells — use this advantage',
      'Keep your torso still; do not sway or use momentum to lift the weight',
    ],
    'targetMuscles': ['Lateral deltoids', 'Supraspinatus'],
    'swapAlternatives': ['lateral_raises', 'overhead_press'],
    'category': 'push',
  },

  // ─── PUSH — Triceps ──────────────────────────────────────────────────────────

  'tricep_pushdown': {
    'id': 'tricep_pushdown',
    'name': 'Tricep Pushdown',
    'muscle': 'Triceps',
    'equipment': 'full_gym',
    'sets': 3,
    'reps': 12,
    'defaultKg': 30.0,
    'formCues': [
      'Set the cable pulley high and attach a straight bar or rope handle',
      'Keep your elbows pinned firmly at your sides throughout — do not let them flare',
      'Push the bar or rope down until your arms are fully extended',
      'Squeeze the triceps hard at the bottom, then return under full control',
      'Keep your chest up and torso slightly forward — avoid leaning excessively',
    ],
    'targetMuscles': ['Triceps brachii (all three heads)'],
    'swapAlternatives': ['tricep_overhead_extension', 'diamond_push_up'],
    'category': 'push',
  },

  'tricep_overhead_extension': {
    'id': 'tricep_overhead_extension',
    'name': 'Tricep Overhead Extension',
    'muscle': 'Triceps',
    'equipment': 'home_dumbbells',
    'sets': 3,
    'reps': 12,
    'defaultKg': 15.0,
    'formCues': [
      'Hold one dumbbell with both hands cupped around the inner plate above your head',
      'Keep your upper arms vertical and elbows pointing straight up — do not let them flare',
      'Lower the dumbbell behind your head in a controlled arc until you feel a full stretch',
      'Press back up by extending at the elbow — only the forearms should move',
      'This exercise maximally stretches the long head of the triceps for superior growth',
    ],
    'targetMuscles': [
      'Triceps brachii long head',
      'Triceps brachii medial head'
    ],
    'swapAlternatives': ['tricep_pushdown', 'diamond_push_up'],
    'category': 'push',
  },

  'diamond_push_up': {
    'id': 'diamond_push_up',
    'name': 'Diamond Push-Up',
    'muscle': 'Triceps',
    'equipment': 'home_bodyweight',
    'sets': 3,
    'reps': 12,
    'defaultKg': 0.0,
    'formCues': [
      'Place hands close together under your chest, thumbs and index fingers forming a diamond',
      'Keep your elbows tracking back along your torso, not flaring outward',
      'Maintain a rigid plank position — do not let your hips sag or rise',
      'Lower until your chest nearly touches your hands, then press back up explosively',
      'If too difficult, elevate your hands on a bench or surface to reduce load',
    ],
    'targetMuscles': [
      'Triceps brachii',
      'Pectoralis major (inner)',
      'Anterior deltoids'
    ],
    'swapAlternatives': ['tricep_pushdown', 'tricep_overhead_extension'],
    'category': 'push',
  },

  // ─── PULL — Back ─────────────────────────────────────────────────────────────

  'barbell_row': {
    'id': 'barbell_row',
    'name': 'Barbell Row',
    'muscle': 'Back',
    'equipment': 'full_gym',
    'sets': 4,
    'reps': 8,
    'defaultKg': 60.0,
    'formCues': [
      'Hinge at the hips to roughly 45 degrees, keeping a flat, neutral spine',
      'Grip the bar just outside shoulder width with an overhand grip',
      'Pull the bar into your lower chest or upper abdomen — not toward your neck',
      'Lead with your elbows, driving them back and up as you row',
      'Squeeze your shoulder blades together hard at the top of every rep',
    ],
    'targetMuscles': [
      'Latissimus dorsi',
      'Rhomboids',
      'Rear deltoids',
      'Biceps brachii'
    ],
    'swapAlternatives': ['dumbbell_row', 'cable_row'],
    'category': 'pull',
  },

  'dumbbell_row': {
    'id': 'dumbbell_row',
    'name': 'Dumbbell Row',
    'muscle': 'Back',
    'equipment': 'home_dumbbells',
    'sets': 4,
    'reps': 10,
    'defaultKg': 25.0,
    'formCues': [
      'Place one knee and same-side hand on the bench; keep your back flat and parallel to the floor',
      'Let the dumbbell hang with arm fully extended to get a full stretch at the bottom',
      'Pull the dumbbell toward your hip, driving your elbow up and back',
      'Avoid rotating your torso — keep your hips and shoulders square to the bench',
      'Lower the weight under full control to the fully extended position each rep',
    ],
    'targetMuscles': [
      'Latissimus dorsi',
      'Rhomboids',
      'Rear deltoids',
      'Biceps brachii'
    ],
    'swapAlternatives': ['barbell_row', 'cable_row'],
    'category': 'pull',
  },

  'pull_up': {
    'id': 'pull_up',
    'name': 'Pull-Up',
    'muscle': 'Back',
    'equipment': 'home_bodyweight',
    'sets': 3,
    'reps': 8,
    'defaultKg': 0.0,
    'formCues': [
      'Start from a dead hang with arms fully extended and shoulders relaxed',
      'Pull your shoulder blades down and back before initiating the pull',
      'Drive your elbows down toward your hips rather than thinking about pulling with hands',
      'Get your chin clearly above the bar — partial reps do not count',
      'Lower all the way back to a dead hang on every single rep for full range of motion',
    ],
    'targetMuscles': [
      'Latissimus dorsi',
      'Biceps brachii',
      'Rear deltoids',
      'Core'
    ],
    'swapAlternatives': ['lat_pulldown', 'dumbbell_row'],
    'category': 'pull',
  },

  'lat_pulldown': {
    'id': 'lat_pulldown',
    'name': 'Lat Pulldown',
    'muscle': 'Back',
    'equipment': 'full_gym',
    'sets': 4,
    'reps': 10,
    'defaultKg': 50.0,
    'formCues': [
      'Use a grip just outside shoulder-width on the wide bar; avoid excessively wide grip',
      'Lean back slightly — about 10–15 degrees — before initiating the pull',
      'Pull the bar to your upper chest, leading with your elbows driving down and back',
      'Squeeze the lats at the bottom and hold for one count before returning',
      'Let the bar travel all the way back up to full arm extension on every rep',
    ],
    'targetMuscles': [
      'Latissimus dorsi',
      'Biceps brachii',
      'Rear deltoids',
      'Teres major'
    ],
    'swapAlternatives': ['pull_up', 'cable_row'],
    'category': 'pull',
  },

  'cable_row': {
    'id': 'cable_row',
    'name': 'Seated Cable Row',
    'muscle': 'Back',
    'equipment': 'full_gym',
    'sets': 3,
    'reps': 12,
    'defaultKg': 45.0,
    'formCues': [
      'Sit tall with a slight forward lean at the start of each rep for full stretch',
      'Pull the handle into your lower abdomen, not your chest',
      'Drive your elbows back as far as possible and squeeze the shoulder blades together',
      'Hold the contracted position for one count before returning with full control',
      'Avoid rounding your lower back or using excessive body English to complete reps',
    ],
    'targetMuscles': [
      'Latissimus dorsi',
      'Rhomboids',
      'Rear deltoids',
      'Biceps brachii'
    ],
    'swapAlternatives': ['barbell_row', 'dumbbell_row'],
    'category': 'pull',
  },

  'face_pull': {
    'id': 'face_pull',
    'name': 'Face Pull',
    'muscle': 'Rear Delts',
    'equipment': 'full_gym',
    'sets': 3,
    'reps': 15,
    'defaultKg': 20.0,
    'formCues': [
      'Set the cable to upper chest or eye level with a rope attachment',
      'Pull the rope toward your face, separating the ends around your head',
      'Drive your elbows high and wide — they should be at or above shoulder height',
      'Focus on externally rotating your shoulders at peak contraction',
      'Use light to moderate weight — this is a health and posture exercise, not a strength lift',
    ],
    'targetMuscles': [
      'Rear deltoids',
      'Rotator cuff',
      'Middle traps',
      'Rhomboids'
    ],
    'swapAlternatives': ['dumbbell_row', 'barbell_row'],
    'category': 'pull',
  },

  // ─── PULL — Biceps ───────────────────────────────────────────────────────────

  'barbell_curl': {
    'id': 'barbell_curl',
    'name': 'Barbell Curl',
    'muscle': 'Biceps',
    'equipment': 'full_gym',
    'sets': 3,
    'reps': 10,
    'defaultKg': 30.0,
    'formCues': [
      'Stand with feet shoulder-width apart, bar held in an underhand grip outside hip width',
      'Keep your upper arms pinned to your sides — only your forearms should move',
      'Curl the bar up in a smooth arc, squeezing the biceps at the top of each rep',
      'Do not swing your torso or use momentum — if you must, the weight is too heavy',
      'Lower the bar fully under control over 2–3 seconds for maximum bicep stretch',
    ],
    'targetMuscles': ['Biceps brachii', 'Brachialis', 'Brachioradialis'],
    'swapAlternatives': ['dumbbell_curl', 'hammer_curl'],
    'category': 'pull',
  },

  'dumbbell_curl': {
    'id': 'dumbbell_curl',
    'name': 'Dumbbell Curl',
    'muscle': 'Biceps',
    'equipment': 'home_dumbbells',
    'sets': 3,
    'reps': 12,
    'defaultKg': 12.0,
    'formCues': [
      'Alternate arms or perform both simultaneously — both techniques are valid',
      'Supinate your wrist (rotate palm upward) as you curl for full bicep contraction',
      'Keep your elbows stationary at your sides — do not let them travel forward',
      'Squeeze hard at the top with the pinky side of your hand slightly higher',
      'Lower fully to a complete stretch at the bottom — do not short-circuit the range',
    ],
    'targetMuscles': ['Biceps brachii', 'Brachialis'],
    'swapAlternatives': ['barbell_curl', 'incline_dumbbell_curl'],
    'category': 'pull',
  },

  'hammer_curl': {
    'id': 'hammer_curl',
    'name': 'Hammer Curl',
    'muscle': 'Biceps',
    'equipment': 'home_dumbbells',
    'sets': 3,
    'reps': 12,
    'defaultKg': 12.0,
    'formCues': [
      'Hold dumbbells in a neutral grip (palms facing each other) throughout the entire movement',
      'Keep your upper arms pinned to your sides with elbows pointing straight down',
      'Curl the dumbbells up without supinating the wrist — maintain the neutral grip',
      'The neutral grip targets the brachialis and brachioradialis more than standard curls',
      'Lower with control and pause at the bottom to eliminate momentum on each rep',
    ],
    'targetMuscles': ['Brachialis', 'Brachioradialis', 'Biceps brachii'],
    'swapAlternatives': ['dumbbell_curl', 'barbell_curl'],
    'category': 'pull',
  },

  'incline_dumbbell_curl': {
    'id': 'incline_dumbbell_curl',
    'name': 'Incline Dumbbell Curl',
    'muscle': 'Biceps',
    'equipment': 'home_dumbbells',
    'sets': 3,
    'reps': 12,
    'defaultKg': 10.0,
    'formCues': [
      'Set bench to 45–60 degrees and sit back with arms hanging straight down behind you',
      'This position stretches the long head of the bicep for a superior growth stimulus',
      'Curl both dumbbells simultaneously, supinating as you lift',
      'Do not let your elbows drift forward — keep them behind your torso line',
      'Lower to a full dead hang at the bottom before initiating the next rep',
    ],
    'targetMuscles': ['Biceps brachii long head', 'Brachialis'],
    'swapAlternatives': ['dumbbell_curl', 'hammer_curl'],
    'category': 'pull',
  },

  // ─── LEGS — Quads ────────────────────────────────────────────────────────────

  'barbell_squat': {
    'id': 'barbell_squat',
    'name': 'Barbell Back Squat',
    'muscle': 'Quads',
    'equipment': 'full_gym',
    'sets': 4,
    'reps': 8,
    'defaultKg': 80.0,
    'formCues': [
      'Position the bar on your upper traps (high bar) or rear delts (low bar) — not on your neck',
      'Brace your core as if you are about to be punched, then take a deep breath and hold it',
      'Push your knees out in the direction of your little toes as you descend',
      'Squat until your hips are at or below parallel — do not cut depth short',
      'Drive through your entire foot on the ascent — do not rise on your toes',
    ],
    'targetMuscles': [
      'Quadriceps',
      'Glutes',
      'Hamstrings',
      'Core',
      'Erector spinae'
    ],
    'swapAlternatives': ['goblet_squat', 'leg_press'],
    'category': 'legs',
  },

  'goblet_squat': {
    'id': 'goblet_squat',
    'name': 'Goblet Squat',
    'muscle': 'Quads',
    'equipment': 'home_dumbbells',
    'sets': 3,
    'reps': 12,
    'defaultKg': 20.0,
    'formCues': [
      'Hold a dumbbell vertically at your chest with both hands cupping the top end',
      'Stand with feet slightly wider than shoulder-width, toes turned out 15–30 degrees',
      'Keep the dumbbell tight to your chest — do not let it pull you forward',
      'Drive your elbows inside your knees at the bottom to help open up your hips',
      'Press through your full foot as you stand — squeeze your glutes at the top',
    ],
    'targetMuscles': ['Quadriceps', 'Glutes', 'Core', 'Adductors'],
    'swapAlternatives': ['bodyweight_squat', 'barbell_squat'],
    'category': 'legs',
  },

  'bodyweight_squat': {
    'id': 'bodyweight_squat',
    'name': 'Bodyweight Squat',
    'muscle': 'Quads',
    'equipment': 'home_bodyweight',
    'sets': 3,
    'reps': 15,
    'defaultKg': 0.0,
    'formCues': [
      'Stand feet shoulder-width apart, toes slightly turned out for natural hip tracking',
      'Keep your chest up and look straight ahead — not down at the floor',
      'Push your knees outward in line with your toes as you descend',
      'Aim for hips below parallel while keeping your heels on the ground',
      'Use this movement to develop squat pattern before adding load',
    ],
    'targetMuscles': ['Quadriceps', 'Glutes', 'Hamstrings'],
    'swapAlternatives': ['goblet_squat', 'walking_lunge'],
    'category': 'legs',
  },

  'leg_press': {
    'id': 'leg_press',
    'name': 'Leg Press',
    'muscle': 'Quads',
    'equipment': 'full_gym',
    'sets': 4,
    'reps': 10,
    'defaultKg': 100.0,
    'formCues': [
      'Place feet shoulder-width apart, mid-platform — higher feet target glutes more',
      'Keep your lower back flat against the pad at all times during the movement',
      'Lower the sled until your knees form roughly a 90-degree angle or slightly beyond',
      'Press through the full platform evenly — do not let knees cave inward',
      'Never lock out your knees at the top — maintain a slight bend to protect the joint',
    ],
    'targetMuscles': ['Quadriceps', 'Glutes', 'Hamstrings'],
    'swapAlternatives': ['barbell_squat', 'goblet_squat'],
    'category': 'legs',
  },

  'leg_extension': {
    'id': 'leg_extension',
    'name': 'Leg Extension',
    'muscle': 'Quads',
    'equipment': 'full_gym',
    'sets': 3,
    'reps': 12,
    'defaultKg': 40.0,
    'formCues': [
      'Adjust seat so the pad rests just above the ankle and knee is at the seat edge',
      'Extend both legs fully until they are straight, squeezing the quads at the top',
      'Hold the peak contraction for one second before lowering with control',
      'Lower slowly — 3 seconds down — for maximum quad time under tension',
      'Keep toes pointed forward or slightly upward; avoid excessive plantarflexion',
    ],
    'targetMuscles': ['Quadriceps (all four heads)'],
    'swapAlternatives': ['barbell_squat', 'leg_press'],
    'category': 'legs',
  },

  // ─── LEGS — Hamstrings ───────────────────────────────────────────────────────

  'romanian_deadlift': {
    'id': 'romanian_deadlift',
    'name': 'Romanian Deadlift',
    'muscle': 'Hamstrings',
    'equipment': 'full_gym',
    'sets': 3,
    'reps': 10,
    'defaultKg': 60.0,
    'formCues': [
      'Hold the bar at hip level with a double overhand grip, arms straight',
      'Push your hips back behind you while maintaining a completely flat back',
      'Let the bar slide down your thighs — keep it in contact with your legs throughout',
      'Lower until you feel a strong hamstring stretch, typically mid-shin for most people',
      'Drive your hips forward forcefully to return to standing — squeeze glutes at the top',
    ],
    'targetMuscles': ['Hamstrings', 'Glutes', 'Erector spinae'],
    'swapAlternatives': ['dumbbell_romanian_deadlift', 'leg_curl'],
    'category': 'legs',
  },

  'dumbbell_romanian_deadlift': {
    'id': 'dumbbell_romanian_deadlift',
    'name': 'Dumbbell Romanian Deadlift',
    'muscle': 'Hamstrings',
    'equipment': 'home_dumbbells',
    'sets': 3,
    'reps': 10,
    'defaultKg': 20.0,
    'formCues': [
      'Hold dumbbells in front of your thighs with a neutral grip, arms straight',
      'Hinge at the hips, pushing them back while keeping a flat, neutral spine',
      'Let the dumbbells travel down close to your legs in a straight vertical path',
      'Feel the hamstring stretch fully before reversing — depth is determined by your flexibility',
      'Drive hips forward to stand, squeezing glutes hard at the top of every rep',
    ],
    'targetMuscles': ['Hamstrings', 'Glutes', 'Erector spinae'],
    'swapAlternatives': ['romanian_deadlift', 'leg_curl'],
    'category': 'legs',
  },

  'leg_curl': {
    'id': 'leg_curl',
    'name': 'Lying Leg Curl',
    'muscle': 'Hamstrings',
    'equipment': 'full_gym',
    'sets': 3,
    'reps': 12,
    'defaultKg': 40.0,
    'formCues': [
      'Lie face down with the pad resting just above your heels at ankle level',
      'Keep your hips pressed into the pad — do not let them rise as you curl',
      'Curl your heels toward your glutes through the full range of motion',
      'Squeeze your hamstrings hard at peak contraction before lowering',
      'Lower under full control — avoid letting the weight slam down between reps',
    ],
    'targetMuscles': [
      'Hamstrings (biceps femoris, semitendinosus, semimembranosus)'
    ],
    'swapAlternatives': ['romanian_deadlift', 'dumbbell_romanian_deadlift'],
    'category': 'legs',
  },

  // ─── LEGS — Full / Compound ──────────────────────────────────────────────────

  'barbell_deadlift': {
    'id': 'barbell_deadlift',
    'name': 'Barbell Deadlift',
    'muscle': 'Full Back',
    'equipment': 'full_gym',
    'sets': 3,
    'reps': 5,
    'defaultKg': 100.0,
    'formCues': [
      'Stand with the bar over your mid-foot, feet hip-width apart',
      'Hinge down and grip the bar just outside your legs — engage lats by trying to "bend" the bar',
      'Take a big breath, brace your core maximally, then push the floor away as you lift',
      'The bar must stay in contact with your legs from floor to lockout — no swinging out',
      'At lockout, stand tall with hips fully extended and glutes squeezed — do not hyperextend',
    ],
    'targetMuscles': [
      'Hamstrings',
      'Glutes',
      'Erector spinae',
      'Lats',
      'Traps',
      'Quadriceps'
    ],
    'swapAlternatives': ['romanian_deadlift', 'barbell_squat'],
    'category': 'legs',
  },

  'hip_thrust': {
    'id': 'hip_thrust',
    'name': 'Hip Thrust',
    'muscle': 'Glutes',
    'equipment': 'home_dumbbells',
    'sets': 3,
    'reps': 12,
    'defaultKg': 30.0,
    'formCues': [
      'Rest your upper back on a bench, feet flat on the floor hip-width apart',
      'Place a dumbbell on your hip flexors and hold it steady with both hands',
      'Drive through your heels to lift your hips, squeezing your glutes at the top',
      'At the top, form a straight line from shoulders to knees — do not hyperextend',
      'Lower hips toward the ground under control without fully resting between reps',
    ],
    'targetMuscles': ['Glutes', 'Hamstrings', 'Core'],
    'swapAlternatives': ['barbell_squat', 'romanian_deadlift'],
    'category': 'legs',
  },

  'walking_lunge': {
    'id': 'walking_lunge',
    'name': 'Walking Lunge',
    'muscle': 'Legs',
    'equipment': 'home_dumbbells',
    'sets': 3,
    'reps': 12,
    'defaultKg': 15.0,
    'formCues': [
      'Hold a dumbbell in each hand at your sides and stand tall with core engaged',
      'Step forward far enough so your front shin stays vertical when your knee is at 90 degrees',
      'Lower your rear knee to within an inch of the floor without letting it crash down',
      'Drive through your front heel to step forward into the next rep',
      'Keep your torso upright throughout — do not lean forward over the front knee',
    ],
    'targetMuscles': ['Quadriceps', 'Glutes', 'Hamstrings', 'Calves'],
    'swapAlternatives': ['goblet_squat', 'bodyweight_squat'],
    'category': 'legs',
  },

  'calf_raise': {
    'id': 'calf_raise',
    'name': 'Calf Raise',
    'muscle': 'Calves',
    'equipment': 'home_bodyweight',
    'sets': 4,
    'reps': 15,
    'defaultKg': 0.0,
    'formCues': [
      'Stand on the edge of a step with heels off the edge for full range of motion',
      'Lower your heels as far as possible below the step before each rep',
      'Rise up onto your tiptoes as high as possible and pause at the top',
      'Perform each rep slowly — 2 seconds up, 2 seconds down — calves respond to time under tension',
      'Avoid bouncing at the bottom — the deep stretch is the most important part',
    ],
    'targetMuscles': ['Gastrocnemius', 'Soleus'],
    'swapAlternatives': ['walking_lunge', 'leg_press'],
    'category': 'legs',
  },

  // ─── CORE ─────────────────────────────────────────────────────────────────────

  'plank': {
    'id': 'plank',
    'name': 'Plank',
    'muscle': 'Core',
    'equipment': 'home_bodyweight',
    'sets': 3,
    'reps': 60,
    'defaultKg': 0.0,
    'formCues': [
      'Support yourself on your forearms and toes with elbows directly under your shoulders',
      'Squeeze your glutes, brace your abs, and squeeze your legs together for full tension',
      'Do not let your hips sag toward the floor or pike up toward the ceiling',
      'Keep your neck neutral — do not look up or tuck your chin excessively',
      'Breathe steadily — do not hold your breath; aim for a slow rhythmic exhale',
    ],
    'targetMuscles': [
      'Rectus abdominis',
      'Transverse abdominis',
      'Obliques',
      'Erector spinae'
    ],
    'swapAlternatives': ['ab_wheel', 'cable_crunch'],
    'category': 'core',
  },

  'ab_wheel': {
    'id': 'ab_wheel',
    'name': 'Ab Wheel Rollout',
    'muscle': 'Core',
    'equipment': 'home_bodyweight',
    'sets': 3,
    'reps': 12,
    'defaultKg': 0.0,
    'formCues': [
      'Start on your knees with the wheel directly below your shoulders',
      'Brace your core maximally before rolling out — think about crushing your abs',
      'Roll forward as far as you can while maintaining a flat lower back — do not hyperextend',
      'Use your abs to pull the wheel back to the start, not your hip flexors',
      'Progress by rolling out further over weeks — a full rollout to horizontal is very advanced',
    ],
    'targetMuscles': [
      'Rectus abdominis',
      'Transverse abdominis',
      'Lats',
      'Hip flexors'
    ],
    'swapAlternatives': ['plank', 'hanging_knee_raise'],
    'category': 'core',
  },

  'hanging_knee_raise': {
    'id': 'hanging_knee_raise',
    'name': 'Hanging Knee Raise',
    'muscle': 'Core',
    'equipment': 'full_gym',
    'sets': 3,
    'reps': 12,
    'defaultKg': 0.0,
    'formCues': [
      'Hang from a pull-up bar with arms fully extended and body straight',
      'Brace your core and pull your knees up toward your chest in a controlled arc',
      'Avoid swinging your body to generate momentum — control the movement completely',
      'Pause briefly at the top with knees at chest level before lowering',
      'Lower your legs fully back to hanging position to complete each rep',
    ],
    'targetMuscles': ['Rectus abdominis', 'Hip flexors', 'Obliques'],
    'swapAlternatives': ['ab_wheel', 'cable_crunch'],
    'category': 'core',
  },

  'cable_crunch': {
    'id': 'cable_crunch',
    'name': 'Cable Crunch',
    'muscle': 'Core',
    'equipment': 'full_gym',
    'sets': 3,
    'reps': 15,
    'defaultKg': 25.0,
    'formCues': [
      'Attach a rope to a high pulley, kneel facing the machine, and hold the rope at your ears',
      'Hinge at the waist, crunching your rib cage down toward your hips — not your head toward the floor',
      'Keep your hips stationary and over your knees throughout the movement',
      'Squeeze your abs hard at the fully contracted position before returning',
      'Control the return — do not let the weight stack pull you up explosively',
    ],
    'targetMuscles': ['Rectus abdominis', 'Obliques'],
    'swapAlternatives': ['plank', 'ab_wheel'],
    'category': 'core',
  },

  'russian_twist': {
    'id': 'russian_twist',
    'name': 'Russian Twist',
    'muscle': 'Core',
    'equipment': 'home_bodyweight',
    'sets': 3,
    'reps': 20,
    'defaultKg': 0.0,
    'formCues': [
      'Sit with knees bent, heels slightly off the ground, and torso leaned back 45 degrees',
      'Keep your spine straight — avoid rounding your lower back under load',
      'Rotate your torso from side to side, touching the ground beside each hip',
      'Move from your torso, not just your arms — create real rotation through your obliques',
      'Add a weight plate or dumbbell once bodyweight becomes easy — progress gradually',
    ],
    'targetMuscles': ['Obliques', 'Rectus abdominis', 'Hip flexors'],
    'swapAlternatives': ['plank', 'cable_crunch'],
    'category': 'core',
  },
};
