import 'dart:io';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';
import '../../shared/models/set_log.dart';
import '../../shared/models/user_profile.dart';
import '../../shared/repositories/workout_repository.dart';

class ExportService {
  /// Generates a CSV file containing all workout logs and sets and triggers sharing.
  static Future<void> exportCsv() async {
    final buffer = StringBuffer();
    // CSV Header
    buffer.writeln('Date,Workout Name,Duration (min),Exercise,Sets,Reps,Weight (kg),RPE');

    final workoutRepo = WorkoutRepository();

    final logs = workoutRepo.getAll()
      ..sort((a, b) => b.startedAt.compareTo(a.startedAt)); // Newest first

    for (final log in logs) {
      final duration = log.completedAt?.difference(log.startedAt).inMinutes ?? 0;
      final dateStr = log.startedAt.toIso8601String().split('T')[0];

      final sets = workoutRepo.getSetsForWorkout(log.id)
          .where((s) => s.completed)
          .toList();

      if (sets.isEmpty) continue;

      // Group sets by exercise
      final setsByExercise = <String, List<SetLog>>{};
      for (final s in sets) {
        setsByExercise.putIfAbsent(s.exerciseId, () => []).add(s);
      }

      for (final entry in setsByExercise.entries) {
        final exerciseId = entry.key;
        final exSets = entry.value;
        // Format ID e.g., 'barbell_bench_press' -> 'Barbell Bench Press'
        final exName = exerciseId.split('_').map((word) => 
          word.isNotEmpty ? '${word[0].toUpperCase()}${word.substring(1)}' : ''
        ).join(' ');

        // Write a row per exercise summary for this workout
        for (final s in exSets) {
          buffer.writeln(
            '$dateStr,"${log.programDayName}",$duration,"$exName",1,${s.reps},${s.weightKg},'
          );
        }
      }
    }

    final directory = await getApplicationDocumentsDirectory();
    final file = File('${directory.path}/forja_workout_data.csv');
    await file.writeAsString(buffer.toString());

    await SharePlus.instance.share(ShareParams(files: [XFile(file.path)], text: 'My FORJA Workout Data'));
  }

  /// Generates a PDF summary report and triggers sharing.
  static Future<void> exportPdf(UserProfile? profile) async {
    final pdf = pw.Document();

    final workoutRepo = WorkoutRepository();

    final logs = workoutRepo.getAll()
      ..sort((a, b) => b.startedAt.compareTo(a.startedAt));

    final totalWorkouts = logs.length;
    var totalVolume = 0.0;
    
    // Calculate total volume across all logs
    for (final log in logs) {
      final sets = workoutRepo.getSetsForWorkout(log.id).where((s) => s.completed);
      for (final s in sets) {
        totalVolume += (s.weightKg * s.reps);
      }
    }

    pdf.addPage(
      pw.Page(
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Header(
                level: 0,
                child: pw.Text('FORJA Fitness Report', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
              ),
              pw.SizedBox(height: 20),
              pw.Text('Athlete: ${profile?.name ?? 'Unknown'}', style: pw.TextStyle(fontSize: 14)),
              pw.Text('Level: ${profile?.level ?? 'Novice'} | XP: ${profile?.xp ?? 0}', style: pw.TextStyle(fontSize: 14)),
              pw.SizedBox(height: 20),
              pw.Text('Summary Statistics', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
              pw.Bullet(text: 'Total Workouts: $totalWorkouts'),
              pw.Bullet(text: 'Total Volume Lifted: ${(totalVolume / 1000).toStringAsFixed(1)} tonnes'),
              pw.SizedBox(height: 20),
              pw.Text('Recent Workouts', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 10),
              ...logs.take(10).map((log) {
                final dateStr = log.startedAt.toIso8601String().split('T')[0];
                return pw.Padding(
                  padding: const pw.EdgeInsets.only(bottom: 8),
                  child: pw.Text('• $dateStr - ${log.programDayName}', style: const pw.TextStyle(fontSize: 12)),
                );
              }),
              pw.Spacer(),
              pw.Align(
                alignment: pw.Alignment.center,
                child: pw.Text('Generated by FORJA', style: pw.TextStyle(fontSize: 10, color: PdfColors.grey)),
              ),
            ],
          );
        },
      ),
    );

    final directory = await getApplicationDocumentsDirectory();
    final file = File('${directory.path}/forja_report.pdf');
    await file.writeAsBytes(await pdf.save());

    await SharePlus.instance.share(ShareParams(files: [XFile(file.path)], text: 'My FORJA Report'));
  }
}
